version: '3.8'

services:
  web:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/tutoreal
    container_name: tutoreal-nginx
    depends_on:
      - app
      - db
  app:
    build: 
      context: _docker
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/tutoreal
    user: 1000:1000
    depends_on:
      - db
    container_name: tutoreal-php
    environment:
      - PATH="$PATH:/usr/local/bin"
  db:
    image: mysql:8.0
    # restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    ports:
      - 3316:3306
    environment:
      MYSQL_DATABASE: tutoreal
      MYSQL_ROOT_PASSWORD: tutoreal
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: tutoreal-mysql
  composer:
    build:
      context: _docker
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/tutoreal
    user: 1000:1000
    container_name: tutoreal-composer
  artisan:
    build:
      context: _docker
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/tutoreal
    user: 1000:1000
    entrypoint: ["php", "/var/www/tutoreal/artisan"]
    container_name: tutoreal-artisan